# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileAxxess' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileAxxess
	pod 'MBProgressHUD'

  target 'MobileAxxessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileAxxessUITests' do
    # Pods for testing
  end

end
